from reportlab.lib.pagesizes import letter
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, Frame, PageTemplate, BaseDocTemplate
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.platypus.doctemplate import _doNothing
import io
import os
import json
from datetime import datetime, timezone
from openai import OpenAI
from dotenv import load_dotenv
from app.models.coding_challenge import CodingSubmission
from sqlalchemy.orm import Session

load_dotenv()
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))


class ReportDocTemplate(BaseDocTemplate):
    """Custom doc template with page numbers, headers, and footers."""

    def __init__(self, filename, title="AI Career Report", **kwargs):
        self.report_title = title
        super().__init__(filename, **kwargs)
        frame = Frame(
            self.leftMargin, self.bottomMargin,
            self.width, self.height,
            id='normal'
        )
        template = PageTemplate(id='default', frames=frame, onPage=self._draw_header_footer)
        self.addPageTemplates([template])

    def _draw_header_footer(self, canvas, doc):
        canvas.saveState()
        page_width, page_height = letter

        # Header line
        canvas.setStrokeColor(colors.HexColor('#1e40af'))
        canvas.setLineWidth(1.5)
        canvas.line(self.leftMargin, page_height - 0.5 * inch,
                    page_width - self.rightMargin, page_height - 0.5 * inch)

        # Header text
        canvas.setFont('Helvetica', 8)
        canvas.setFillColor(colors.HexColor('#6b7280'))
        canvas.drawString(self.leftMargin, page_height - 0.45 * inch, self.report_title)
        canvas.drawRightString(page_width - self.rightMargin, page_height - 0.45 * inch,
                               "AI Career Preparation Platform")

        # Footer line
        canvas.setStrokeColor(colors.HexColor('#e5e7eb'))
        canvas.setLineWidth(0.5)
        canvas.line(self.leftMargin, 0.5 * inch,
                    page_width - self.rightMargin, 0.5 * inch)

        # Footer text
        canvas.setFont('Helvetica', 8)
        canvas.setFillColor(colors.HexColor('#9ca3af'))
        canvas.drawString(self.leftMargin, 0.35 * inch, "Generated by AI Career Preparation Platform")
        canvas.drawRightString(page_width - self.rightMargin, 0.35 * inch,
                               f"Page {doc.page}")

        canvas.restoreState()


class ReportService:
    @staticmethod
    def generate_ai_summary(session, questions):
        """Summarize the interview session using AI."""
        api_key = os.getenv("OPENAI_API_KEY")

        history = []
        for q in questions:
            history.append({
                "type": "theory",
                "topic": q.topic or "General",
                "question": q.question_text[:500],
                "answer": (q.answer_text or "")[:500],
                "score": q.score,
                "feedback": q.feedback
            })

        from app.database import SessionLocal
        db = SessionLocal()
        coding_subs = db.query(CodingSubmission).filter(CodingSubmission.session_id == session.id).all()
        for sub in coding_subs:
            history.append({
                "type": "coding",
                "challenge": sub.challenge.title if sub.challenge else "Coding Task",
                "code": sub.code[:1000],
                "status": sub.status,
                "output": sub.output
            })
        db.close()

        # Build session-based fallback when AI is unavailable
        def _build_session_fallback():
            strengths = []
            weaknesses = []
            roadmap = []
            scored_qs = [h for h in history if h.get("score") is not None]
            avg_score = sum(h["score"] for h in scored_qs) / len(scored_qs) if scored_qs else 0

            high_qs = sorted([h for h in scored_qs if h["score"] >= 7], key=lambda x: x["score"], reverse=True)
            low_qs = sorted([h for h in scored_qs if h["score"] < 7], key=lambda x: x["score"])

            seen_topics_strengths = set()
            for h in high_qs[:3]:
                topic = h.get('topic', 'technical')
                feedback = (h.get('feedback') or 'solid answer')[:80]
                if topic in seen_topics_strengths:
                    strengths.append(f"Strong {topic} follow-up (scored {h['score']}/10 — {feedback})")
                else:
                    seen_topics_strengths.add(topic)
                    strengths.append(f"Strong {topic} response (scored {h['score']}/10 — {feedback})")

            seen_topics_weak = set()
            for h in low_qs[:3]:
                topic = h.get('topic', 'technical')
                feedback = (h.get('feedback') or 'requires more depth')[:80]
                if topic in seen_topics_weak:
                    weaknesses.append(f"{topic} follow-up needs improvement (scored {h['score']}/10 — {feedback})")
                    roadmap.append(f"Practice {topic} with advanced scenarios and edge cases")
                else:
                    seen_topics_weak.add(topic)
                    weaknesses.append(f"{topic} needs improvement (scored {h['score']}/10 — {feedback})")
                    roadmap.append(f"Review {topic} fundamentals and practice with structured examples")

            if not strengths:
                strengths = ["Demonstrated willingness to engage with all questions"]
            if not weaknesses:
                weaknesses = ["Continue practicing advanced-level questions"]
            if not roadmap:
                roadmap = ["Review weak topics with focused notes", "Practice timed answers with clear structure"]

            total_scored = len(scored_qs)
            confidence = max(0, min(100, round(avg_score * 10))) if total_scored > 0 else 50

            return {
                "summary": f"Candidate attempted {len(history)} questions for the {session.role} role with an average score of {avg_score:.1f}/10 across {total_scored} graded questions.",
                "strengths": strengths,
                "weaknesses": weaknesses,
                "roadmap": roadmap,
                "confidence_score": confidence,
            }

        if not api_key:
            fallback = _build_session_fallback()
            fallback["summary"] = "AI summary not available (API key missing). Showing session-based analysis."
            return fallback

        prompt = f"""You are an expert interview coach. Analyze this {session.role} interview session and give specific, actionable feedback.

INTERVIEW DATA:
{json.dumps(history, indent=2)}

INSTRUCTIONS — be specific and reference actual question topics and scores:
1. summary: 2-3 sentences about the candidate's overall performance. Mention their strongest and weakest topic areas by name. Reference specific scores.
2. weaknesses: Exactly 3 items. Each must reference a specific topic they scored lowest on, with their actual score, and WHY they lost points based on their answer and feedback.
3. strengths: Exactly 3 items. Each must reference a specific topic they scored highest on, with their actual score, and WHAT they did well based on their answer and feedback.
4. roadmap: Exactly 3 items. Each must be a specific actionable step tied to their weakest topics (not generic advice).
5. confidence_score: Overall score 0-100 based on average performance.

Return ONLY a JSON object with keys: "summary", "strengths", "weaknesses", "roadmap", "confidence_score".
Each strengths/weaknesses/roadmap item must be a specific string, not a generic statement."""

        try:
            response = client.chat.completions.create(
                model="gpt-3.5-turbo",
                messages=[{"role": "user", "content": prompt}],
                response_format={"type": "json_object"}
            )
            result = json.loads(response.choices[0].message.content)
            # Validate AI returned reasonable data
            if not result.get("strengths") or not result.get("weaknesses"):
                raise ValueError("AI returned empty strengths or weaknesses")
            return result
        except Exception as e:
            print(f"[REPORT] AI summary failed ({e}), using session-based fallback")
            return _build_session_fallback()

    @staticmethod
    def generate_pdf_report(session, questions):
        ai_summary = ReportService.generate_ai_summary(session, questions)
        return ReportService.create_pdf_report(session, questions, ai_summary)

    @staticmethod
    def create_pdf_report(session, questions, ai_summary):
        buffer = io.BytesIO()
        doc = ReportDocTemplate(buffer, title="AI Performance Report", pagesize=letter,
                                topMargin=0.75*inch, bottomMargin=0.75*inch)
        styles = getSampleStyleSheet()
        elements = []

        elements.append(Paragraph(f"AI Performance Report: {session.role}", styles['Title']))
        elements.append(Spacer(1, 12))

        data = [
            ["Platform", "AI Career Preparation Platform"],
            ["Role", session.role],
            ["Overall Score", f"{session.score}/10" if session.score else "N/A"],
            ["Confidence Analysis", str(ai_summary.get('confidence_score', 'N/A'))],
            ["Date", session.started_at.strftime("%Y-%m-%d") if session.started_at else "N/A"]
        ]
        t = Table(data, colWidths=[150, 300])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#f3f4f6')),
            ('INNERGRID', (0, 0), (-1, -1), 0.25, colors.HexColor('#d1d5db')),
            ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#9ca3af')),
            ('PADDING', (0, 0), (-1, -1), 8),
        ]))
        elements.append(t)
        elements.append(Spacer(1, 24))

        elements.append(Paragraph("Executive Summary", styles['Heading2']))
        elements.append(Paragraph(ai_summary.get('summary', 'No summary available.'), styles['Normal']))
        elements.append(Spacer(1, 12))

        elements.append(Paragraph("Analysis & Roadmap", styles['Heading2']))
        if isinstance(ai_summary.get('strengths'), list):
            strengths_text = "; ".join(ai_summary['strengths'])
        else:
            strengths_text = str(ai_summary.get('strengths', 'N/A'))
        elements.append(Paragraph(f"<b>Strengths:</b> {strengths_text}", styles['Normal']))
        elements.append(Spacer(1, 6))
        if isinstance(ai_summary.get('weaknesses'), list):
            weaknesses_text = "; ".join(ai_summary['weaknesses'])
        else:
            weaknesses_text = str(ai_summary.get('weaknesses', 'N/A'))
        elements.append(Paragraph(f"<b>Weaknesses:</b> {weaknesses_text}", styles['Normal']))
        elements.append(Spacer(1, 6))
        if isinstance(ai_summary.get('roadmap'), list):
            roadmap_text = "; ".join(ai_summary['roadmap'])
        else:
            roadmap_text = str(ai_summary.get('roadmap', 'N/A'))
        elements.append(Paragraph(f"<b>Improvement Roadmap:</b> {roadmap_text}", styles['Normal']))
        elements.append(Spacer(1, 24))

        elements.append(Paragraph("Detailed Question Breakdown", styles['Heading2']))
        for i, q in enumerate(questions):
            elements.append(Paragraph(f"Q{i+1}: {q.question_text}", styles['Heading3']))
            score_display = f"{q.score}/10" if q.score is not None else "Not Graded"
            elements.append(Paragraph(f"Score: {score_display}", styles['Normal']))
            elements.append(Paragraph(f"Topic: {q.topic} | Difficulty: {q.difficulty}", styles['Normal']))
            elements.append(Paragraph(f"<b>Candidate Answer:</b> {q.answer_text[:500]}", styles['Normal']))
            elements.append(Paragraph(f"<b>AI Feedback:</b> {q.feedback}", styles['Normal']))
            elements.append(Spacer(1, 12))

        doc.build(elements)
        buffer.seek(0)
        return buffer

    @staticmethod
    def _capture_scores_snapshot(db: Session, user) -> dict:
        """Capture a snapshot of all current scores for the report."""
        from app.models.career import (
            ResumeAnalysis, SkillGapAnalysis, CareerReadiness
        )

        latest_analysis = db.query(ResumeAnalysis).filter(
            ResumeAnalysis.user_id == user.id
        ).order_by(ResumeAnalysis.created_at.desc()).first()
        latest_gap = db.query(SkillGapAnalysis).filter(
            SkillGapAnalysis.user_id == user.id
        ).order_by(SkillGapAnalysis.created_at.desc()).first()
        readiness = db.query(CareerReadiness).filter(
            CareerReadiness.user_id == user.id
        ).order_by(CareerReadiness.created_at.desc()).first()

        scores = {}
        if latest_analysis:
            if latest_analysis.resume_match_score is not None:
                scores["resume_match"] = latest_analysis.resume_match_score
            if latest_analysis.ats_score is not None:
                scores["ats_score"] = latest_analysis.ats_score
        if latest_gap and latest_gap.match_percentage is not None:
            scores["skill_gap_match"] = latest_gap.match_percentage
        if readiness:
            if readiness.overall_score is not None:
                scores["overall_readiness"] = readiness.overall_score
            if readiness.interview_score is not None:
                scores["interview_score"] = readiness.interview_score
            if readiness.coding_score is not None:
                scores["coding_score"] = readiness.coding_score
            if readiness.learning_score is not None:
                scores["learning_score"] = readiness.learning_score

        return scores

    @staticmethod
    def generate_interview_report(db: Session, user) -> io.BytesIO:
        """Generate an interview-only report."""
        from app.models.interview_session import InterviewSession
        from app.models.question import Question

        session = db.query(InterviewSession).filter(
            InterviewSession.user_id == user.id,
            InterviewSession.status == "completed"
        ).order_by(InterviewSession.started_at.desc()).first()

        if not session:
            buffer = io.BytesIO()
            doc = ReportDocTemplate(buffer, title="Interview Report", pagesize=letter,
                                    topMargin=0.75*inch, bottomMargin=0.75*inch)
            styles = getSampleStyleSheet()
            elements = []
            elements.append(Paragraph("Interview Performance Report", styles['Title']))
            elements.append(Spacer(1, 24))
            elements.append(Paragraph("No completed interview sessions found.", styles['Normal']))
            elements.append(Spacer(1, 12))
            elements.append(Paragraph("Complete an interview session to generate this report.", styles['Normal']))
            doc.build(elements)
            buffer.seek(0)
            return buffer

        questions = db.query(Question).filter(Question.session_id == session.id).all()
        ai_summary = ReportService.generate_ai_summary(session, questions)
        return ReportService.create_pdf_report(session, questions, ai_summary)

    @staticmethod
    def generate_coding_report(db: Session, user) -> io.BytesIO:
        """Generate a coding performance report."""
        from app.models.coding_challenge import CodingSubmission, CodingSession, CodingChallenge

        sessions = db.query(CodingSession).filter(
            CodingSession.user_id == user.id
        ).order_by(CodingSession.started_at.desc()).all()
        submissions = db.query(CodingSubmission).filter(
            CodingSubmission.user_id == user.id
        ).order_by(CodingSubmission.created_at.desc()).all()

        buffer = io.BytesIO()
        doc = ReportDocTemplate(buffer, title="Coding Performance Report", pagesize=letter,
                                topMargin=0.75*inch, bottomMargin=0.75*inch)
        styles = getSampleStyleSheet()
        elements = []

        elements.append(Paragraph("Coding Performance Report", styles['Title']))
        elements.append(Spacer(1, 12))

        passed = sum(1 for s in submissions if s.status == "Accepted")
        total = len(submissions)
        avg_correctness = sum(s.correctness_score or 0 for s in submissions) / total if total else 0
        avg_ai_score = sum(s.ai_score or 0 for s in submissions) / total if total else 0

        summary_data = [
            ["Metric", "Value"],
            ["Total Sessions", str(len(sessions))],
            ["Total Submissions", str(total)],
            ["Passed", str(passed)],
            ["Pass Rate", f"{(passed/total*100):.1f}%" if total else "N/A"],
            ["Avg Correctness", f"{avg_correctness:.1f}%"],
            ["Avg AI Score", f"{avg_ai_score:.1f}/10"],
        ]
        t = Table(summary_data, colWidths=[200, 200])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1e40af')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('INNERGRID', (0, 0), (-1, -1), 0.25, colors.HexColor('#d1d5db')),
            ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#9ca3af')),
            ('PADDING', (0, 0), (-1, -1), 8),
            ('ALIGN', (1, 0), (1, -1), 'CENTER'),
        ]))
        elements.append(t)
        elements.append(Spacer(1, 20))

        lang_counts = {}
        for s in submissions:
            lang = s.language or "unknown"
            lang_counts[lang] = lang_counts.get(lang, 0) + 1
        if lang_counts:
            elements.append(Paragraph("Language Distribution", styles['Heading2']))
            for lang, count in sorted(lang_counts.items(), key=lambda x: -x[1]):
                elements.append(Paragraph(f"<b>{lang}:</b> {count} submissions", styles['Normal']))
            elements.append(Spacer(1, 12))

        if submissions:
            elements.append(Paragraph("Recent Submissions", styles['Heading2']))
            sub_data = [["Challenge", "Language", "Status", "Correctness", "AI Score"]]
            for s in submissions[:15]:
                try:
                    challenge_title = s.challenge.title if s.challenge else "N/A"
                except Exception:
                    challenge_title = "N/A"
                sub_data.append([
                    challenge_title[:30],
                    s.language or "N/A",
                    s.status or "N/A",
                    f"{s.correctness_score:.0f}%" if s.correctness_score is not None else "N/A",
                    f"{s.ai_score:.1f}/10" if s.ai_score is not None else "N/A",
                ])
            st = Table(sub_data, colWidths=[120, 70, 70, 85, 75])
            st.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1e40af')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('FONTSIZE', (0, 0), (-1, -1), 9),
                ('INNERGRID', (0, 0), (-1, -1), 0.25, colors.HexColor('#d1d5db')),
                ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#9ca3af')),
                ('PADDING', (0, 0), (-1, -1), 6),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f9fafb')]),
            ]))
            elements.append(st)

        doc.build(elements)
        buffer.seek(0)
        return buffer

    @staticmethod
    def generate_ats_report(db: Session, user) -> io.BytesIO:
        """Generate an ATS analysis report."""
        from app.models.ats_report import ATSReport

        reports = db.query(ATSReport).filter(
            ATSReport.user_id == user.id
        ).order_by(ATSReport.created_at.desc()).all()

        latest = reports[0] if reports else None

        buffer = io.BytesIO()
        doc = ReportDocTemplate(buffer, title="ATS Analysis Report", pagesize=letter,
                                topMargin=0.75*inch, bottomMargin=0.75*inch)
        styles = getSampleStyleSheet()
        elements = []

        elements.append(Paragraph("ATS Analysis Report", styles['Title']))
        elements.append(Spacer(1, 12))

        if not latest:
            elements.append(Paragraph("No ATS analysis data available. Upload a resume and job description to generate an ATS report.", styles['Normal']))
            doc.build(elements)
            buffer.seek(0)
            return buffer

        score_data = [
            ["Component", "Score", "Weight"],
            ["Overall ATS Score", f"{latest.overall_score}/100", "—"],
            ["Keyword Match", f"{latest.keyword_score}/100", "35%"],
            ["Skills Match", f"{latest.skills_score}/100", "20%"],
            ["Experience", f"{latest.experience_score}/100", "15%"],
            ["Projects", f"{latest.projects_score}/100", "10%"],
            ["Education", f"{latest.education_score}/100", "5%"],
            ["Formatting", f"{latest.formatting_score}/100", "10%"],
            ["Readability", f"{latest.readability_score}/100", "5%"],
        ]
        t = Table(score_data, colWidths=[180, 120, 80])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1e40af')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('INNERGRID', (0, 0), (-1, -1), 0.25, colors.HexColor('#d1d5db')),
            ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#9ca3af')),
            ('PADDING', (0, 0), (-1, -1), 8),
            ('ALIGN', (1, 0), (-1, -1), 'CENTER'),
        ]))
        elements.append(t)
        elements.append(Spacer(1, 16))

        matched = json.loads(latest.matched_skills) if latest.matched_skills else []
        missing = json.loads(latest.missing_skills) if latest.missing_skills else []
        if matched:
            elements.append(Paragraph(f"<b>Matched Skills ({len(matched)}):</b> {', '.join(matched)}", styles['Normal']))
        if missing:
            elements.append(Paragraph(f"<b>Missing Skills ({len(missing)}):</b> {', '.join(missing)}", styles['Normal']))
        elements.append(Spacer(1, 12))

        recs = json.loads(latest.recommendations) if latest.recommendations else []
        if recs:
            elements.append(Paragraph("Recommendations", styles['Heading2']))
            for i, rec in enumerate(recs[:10], 1):
                priority = rec.get("priority", "").upper()
                message = rec.get("message", str(rec))
                elements.append(Paragraph(f"[{priority}] {i}. {message}", styles['Normal']))

        doc.build(elements)
        buffer.seek(0)
        return buffer

    @staticmethod
    def generate_skill_gap_report(db: Session, user) -> io.BytesIO:
        """Generate a skill gap analysis report."""
        from app.models.career import SkillGapAnalysis

        latest = db.query(SkillGapAnalysis).filter(
            SkillGapAnalysis.user_id == user.id
        ).order_by(SkillGapAnalysis.created_at.desc()).first()

        buffer = io.BytesIO()
        doc = ReportDocTemplate(buffer, title="Skill Gap Analysis Report", pagesize=letter,
                                topMargin=0.75*inch, bottomMargin=0.75*inch)
        styles = getSampleStyleSheet()
        elements = []

        elements.append(Paragraph("Skill Gap Analysis Report", styles['Title']))
        elements.append(Spacer(1, 12))

        if not latest:
            elements.append(Paragraph("No skill gap analysis data available.", styles['Normal']))
            doc.build(elements)
            buffer.seek(0)
            return buffer

        elements.append(Paragraph(f"Match Percentage: <b>{latest.match_percentage:.1f}%</b>" if latest.match_percentage else "Match Percentage: N/A", styles['Normal']))
        elements.append(Spacer(1, 12))

        matched = json.loads(latest.matched_skills) if latest.matched_skills else []
        missing = json.loads(latest.missing_skills) if latest.missing_skills else []
        additional = json.loads(latest.additional_skills) if latest.additional_skills else []

        if matched:
            elements.append(Paragraph(f"<b>Matched Skills ({len(matched)}):</b>", styles['Heading2']))
            elements.append(Paragraph(', '.join(matched), styles['Normal']))
            elements.append(Spacer(1, 8))
        if missing:
            elements.append(Paragraph(f"<b>Missing Skills ({len(missing)}):</b>", styles['Heading2']))
            elements.append(Paragraph(', '.join(missing), styles['Normal']))
            elements.append(Spacer(1, 8))
        if additional:
            elements.append(Paragraph(f"<b>Additional Skills ({len(additional)}):</b>", styles['Heading2']))
            elements.append(Paragraph(', '.join(additional), styles['Normal']))

        doc.build(elements)
        buffer.seek(0)
        return buffer

    @staticmethod
    def generate_career_readiness_report(db: Session, user) -> io.BytesIO:
        """Generate a career readiness report."""
        from app.models.career import CareerReadiness, CareerReadinessHistory

        readiness = db.query(CareerReadiness).filter(
            CareerReadiness.user_id == user.id
        ).order_by(CareerReadiness.created_at.desc()).first()

        history = db.query(CareerReadinessHistory).filter(
            CareerReadinessHistory.user_id == user.id
        ).order_by(CareerReadinessHistory.created_at.desc()).limit(10).all()

        buffer = io.BytesIO()
        doc = ReportDocTemplate(buffer, title="Career Readiness Report", pagesize=letter,
                                topMargin=0.75*inch, bottomMargin=0.75*inch)
        styles = getSampleStyleSheet()
        elements = []

        elements.append(Paragraph("Career Readiness Report", styles['Title']))
        elements.append(Spacer(1, 12))

        if not readiness:
            elements.append(Paragraph("No career readiness data available.", styles['Normal']))
            doc.build(elements)
            buffer.seek(0)
            return buffer

        elements.append(Paragraph(f"Overall Readiness Score: <b>{readiness.overall_score:.1f}%</b>" if readiness.overall_score else "Overall: N/A", styles['Normal']))
        elements.append(Spacer(1, 12))

        score_data = [["Component", "Score"]]
        components = [
            ("Resume Match", readiness.resume_match_score),
            ("ATS Score", readiness.ats_score),
            ("Interview Score", readiness.interview_score),
            ("Coding Score", readiness.coding_score),
            ("Skill Gap Score", readiness.skill_gap_score),
            ("Learning Score", readiness.learning_score),
            ("Project Score", readiness.project_score),
            ("Consistency Score", readiness.consistency_score),
            ("Role Match", readiness.role_match_score),
            ("Company Match", readiness.company_match_score),
        ]
        for label, val in components:
            if val is not None:
                score_data.append([label, f"{val:.1f}%"])

        t = Table(score_data, colWidths=[200, 120])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1e40af')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('INNERGRID', (0, 0), (-1, -1), 0.25, colors.HexColor('#d1d5db')),
            ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#9ca3af')),
            ('PADDING', (0, 0), (-1, -1), 8),
        ]))
        elements.append(t)
        elements.append(Spacer(1, 16))

        if readiness.recommendations:
            recs = json.loads(readiness.recommendations)
            if recs:
                elements.append(Paragraph("Recommendations", styles['Heading2']))
                for i, rec in enumerate(recs[:10], 1):
                    elements.append(Paragraph(f"{i}. {rec}", styles['Normal']))

        if history:
            elements.append(Paragraph("Score History", styles['Heading2']))
            hist_data = [["Date", "Overall", "Resume", "ATS", "Interview", "Coding", "Trigger"]]
            for h in history:
                hist_data.append([
                    h.created_at.strftime('%Y-%m-%d %H:%M') if h.created_at else "N/A",
                    f"{h.overall_score:.1f}%" if h.overall_score else "N/A",
                    f"{h.resume_match_score:.1f}%" if h.resume_match_score else "N/A",
                    f"{h.ats_score:.1f}%" if h.ats_score else "N/A",
                    f"{h.interview_score:.1f}%" if h.interview_score else "N/A",
                    f"{h.coding_score:.1f}%" if h.coding_score else "N/A",
                    h.trigger_event or "N/A",
                ])
            ht = Table(hist_data, colWidths=[90, 55, 55, 50, 60, 55, 80])
            ht.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1e40af')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('FONTSIZE', (0, 0), (-1, -1), 8),
                ('INNERGRID', (0, 0), (-1, -1), 0.25, colors.HexColor('#d1d5db')),
                ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#9ca3af')),
                ('PADDING', (0, 0), (-1, -1), 4),
            ]))
            elements.append(ht)

        doc.build(elements)
        buffer.seek(0)
        return buffer

    @staticmethod
    def generate_comprehensive_report(db: Session, user) -> io.BytesIO:
        """Generate a comprehensive portfolio report combining all modules."""
        from app.models.career import (
            ResumeAnalysis, SkillGapAnalysis, LearningRoadmap, CareerReadiness
        )
        from app.models.interview_session import InterviewSession
        from app.models.coding_challenge import CodingSubmission, CodingChallenge
        from app.models.resume import Resume
        from sqlalchemy import func

        user_resumes = db.query(Resume).filter(Resume.user_id == user.id).all()
        latest_analysis = db.query(ResumeAnalysis).filter(
            ResumeAnalysis.user_id == user.id
        ).order_by(ResumeAnalysis.created_at.desc()).first()
        latest_gap = db.query(SkillGapAnalysis).filter(
            SkillGapAnalysis.user_id == user.id
        ).order_by(SkillGapAnalysis.created_at.desc()).first()
        roadmap = db.query(LearningRoadmap).filter(
            LearningRoadmap.user_id == user.id,
            LearningRoadmap.status == "active"
        ).order_by(LearningRoadmap.created_at.desc()).first()
        readiness = db.query(CareerReadiness).filter(
            CareerReadiness.user_id == user.id
        ).order_by(CareerReadiness.created_at.desc()).first()
        interviews = db.query(InterviewSession).filter(
            InterviewSession.user_id == user.id
        ).order_by(InterviewSession.started_at.desc()).all()
        completed_interviews = [i for i in interviews if i.status == "completed"]
        coding_subs = db.query(CodingSubmission).filter(
            CodingSubmission.user_id == user.id
        ).order_by(CodingSubmission.created_at.desc()).all()

        buffer = io.BytesIO()
        doc = ReportDocTemplate(buffer, title="AI Career Portfolio Report", pagesize=letter,
                                topMargin=0.75*inch, bottomMargin=0.75*inch)
        styles = getSampleStyleSheet()
        elements = []

        title_style = ParagraphStyle(
            'CustomTitle', parent=styles['Title'],
            fontSize=24, textColor=colors.HexColor('#1e40af'),
            spaceAfter=6
        )
        subtitle_style = ParagraphStyle(
            'Subtitle', parent=styles['Normal'],
            fontSize=12, textColor=colors.HexColor('#6b7280'),
            spaceAfter=20
        )
        section_style = ParagraphStyle(
            'SectionHeader', parent=styles['Heading2'],
            fontSize=14, textColor=colors.HexColor('#1e40af'),
            spaceBefore=16, spaceAfter=8,
            borderWidth=1, borderColor=colors.HexColor('#dbeafe'),
            borderPadding=4
        )

        # ─── COVER PAGE ───
        elements.append(Spacer(1, 2*inch))
        elements.append(Paragraph("AI Career Portfolio Report", title_style))
        elements.append(Paragraph("Comprehensive Career Readiness Assessment", subtitle_style))
        elements.append(Spacer(1, 24))

        cover_data = [
            ["Candidate", user.name],
            ["Email", user.email],
            ["Generated", datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')],
            ["Platform", "AI Career Preparation Platform"],
        ]
        cover_table = Table(cover_data, colWidths=[150, 300])
        cover_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#f3f4f6')),
            ('FONTSIZE', (0, 0), (-1, -1), 11),
            ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#d1d5db')),
            ('BOX', (0, 0), (-1, -1), 1, colors.HexColor('#9ca3af')),
            ('PADDING', (0, 0), (-1, -1), 8),
        ]))
        elements.append(cover_table)
        elements.append(PageBreak())

        # ─── SCORES OVERVIEW ───
        elements.append(Paragraph("Scores Overview", section_style))
        elements.append(Spacer(1, 8))

        score_rows = [["Metric", "Score", "Status"]]
        if latest_analysis and latest_analysis.resume_match_score is not None:
            score_rows.append(["Resume Match", f"{latest_analysis.resume_match_score:.1f}%", _score_status(latest_analysis.resume_match_score)])
        if latest_analysis and latest_analysis.ats_score is not None:
            score_rows.append(["ATS Score", f"{latest_analysis.ats_score:.1f}%", _score_status(latest_analysis.ats_score)])
        if latest_gap and latest_gap.match_percentage is not None:
            score_rows.append(["Skill Gap Match", f"{latest_gap.match_percentage:.1f}%", _score_status(latest_gap.match_percentage)])
        if readiness:
            if readiness.overall_score is not None:
                score_rows.append(["Career Readiness", f"{readiness.overall_score:.1f}%", _score_status(readiness.overall_score)])
            if readiness.interview_score is not None:
                score_rows.append(["Interview Score", f"{readiness.interview_score:.1f}%", _score_status(readiness.interview_score)])
            if readiness.coding_score is not None:
                score_rows.append(["Coding Score", f"{readiness.coding_score:.1f}%", _score_status(readiness.coding_score)])
            if readiness.learning_score is not None:
                score_rows.append(["Learning Progress", f"{readiness.learning_score:.1f}%", _score_status(readiness.learning_score)])

        if len(score_rows) > 1:
            score_table = Table(score_rows, colWidths=[180, 100, 100])
            score_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1e40af')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('INNERGRID', (0, 0), (-1, -1), 0.25, colors.HexColor('#d1d5db')),
                ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#9ca3af')),
                ('PADDING', (0, 0), (-1, -1), 6),
                ('ALIGN', (1, 0), (-1, -1), 'CENTER'),
            ]))
            elements.append(score_table)
        else:
            elements.append(Paragraph("No score data available yet. Complete analyses to generate scores.", styles['Normal']))
        elements.append(Spacer(1, 16))

        # ─── RESUME SUMMARY ───
        if latest_analysis:
            elements.append(Paragraph("Resume Analysis", section_style))
            if latest_analysis.summary:
                elements.append(Paragraph(latest_analysis.summary, styles['Normal']))
                elements.append(Spacer(1, 8))
            if latest_analysis.detected_skills:
                skills = json.loads(latest_analysis.detected_skills)
                elements.append(Paragraph(f"<b>Detected Skills ({len(skills)}):</b> {', '.join(skills[:20])}", styles['Normal']))
                elements.append(Spacer(1, 12))

        # ─── SKILL GAP ───
        if latest_gap:
            elements.append(Paragraph("Skill Gap Analysis", section_style))
            if latest_gap.matched_skills:
                matched = json.loads(latest_gap.matched_skills)
                elements.append(Paragraph(f"<b>Matched ({len(matched)}):</b> {', '.join(matched)}", styles['Normal']))
            if latest_gap.missing_skills:
                missing = json.loads(latest_gap.missing_skills)
                elements.append(Paragraph(f"<b>Missing ({len(missing)}):</b> {', '.join(missing)}", styles['Normal']))
            if latest_gap.additional_skills:
                additional = json.loads(latest_gap.additional_skills)
                elements.append(Paragraph(f"<b>Additional ({len(additional)}):</b> {', '.join(additional)}", styles['Normal']))
            elements.append(Spacer(1, 12))

        # ─── LEARNING ROADMAP ───
        if roadmap and roadmap.roadmap_items:
            elements.append(Paragraph("Learning Roadmap", section_style))
            elements.append(Paragraph(
                f"Total Hours: {roadmap.total_hours or 0} | "
                f"Estimated Weeks: {roadmap.estimated_weeks or 0} | "
                f"Progress: {roadmap.progress_percentage or 0:.0f}%",
                styles['Normal']
            ))
            elements.append(Spacer(1, 8))
            items = json.loads(roadmap.roadmap_items)
            for item in items[:10]:
                topic = item.get('topic', 'N/A')
                hours = item.get('hours', 0)
                difficulty = item.get('difficulty', 'N/A')
                elements.append(Paragraph(
                    f"<b>{topic}</b> ({hours}h - {difficulty})",
                    styles['Heading3']
                ))
                if item.get('description'):
                    elements.append(Paragraph(item['description'][:200], styles['Normal']))
                elements.append(Spacer(1, 4))
            elements.append(Spacer(1, 8))

        # ─── INTERVIEW PERFORMANCE ───
        if completed_interviews:
            elements.append(PageBreak())
            elements.append(Paragraph("Interview Performance", section_style))
            avg_score = sum(i.score or 0 for i in completed_interviews) / len(completed_interviews) if completed_interviews else 0
            elements.append(Paragraph(
                f"Completed Interviews: {len(completed_interviews)} | "
                f"Average Score: {avg_score:.1f}/10",
                styles['Normal']
            ))
            elements.append(Spacer(1, 8))
            for interview in completed_interviews[:5]:
                elements.append(Paragraph(
                    f"<b>{interview.role}</b> - Score: {interview.score}/10 - "
                    f"Date: {interview.started_at.strftime('%Y-%m-%d') if interview.started_at else 'N/A'}",
                    styles['Normal']
                ))
                elements.append(Spacer(1, 4))

        # ─── CODING PERFORMANCE ───
        if coding_subs:
            elements.append(Paragraph("Coding Performance", section_style))
            passed = sum(1 for s in coding_subs if s.status == "Accepted")
            elements.append(Paragraph(
                f"Total Submissions: {len(coding_subs)} | "
                f"Passed: {passed} | "
                f"Pass Rate: {(passed/len(coding_subs)*100):.1f}%",
                styles['Normal']
            ))
            elements.append(Spacer(1, 8))
            lang_counts = {}
            for s in coding_subs:
                lang = s.language or "unknown"
                lang_counts[lang] = lang_counts.get(lang, 0) + 1
            if lang_counts:
                lang_str = ", ".join(f"{lang}: {count}" for lang, count in sorted(lang_counts.items(), key=lambda x: -x[1]))
                elements.append(Paragraph(f"<b>Languages Used:</b> {lang_str}", styles['Normal']))
            elements.append(Spacer(1, 12))

        # ─── AI EXECUTIVE SUMMARY ───
        elements.append(Paragraph("AI Executive Summary", section_style))
        exec_summary = ReportService._generate_executive_summary(
            latest_analysis, latest_gap, readiness, completed_interviews, coding_subs
        )
        elements.append(Paragraph(exec_summary, styles['Normal']))
        elements.append(Spacer(1, 12))

        # ─── RECOMMENDATIONS ───
        if readiness:
            all_recs = []
            if readiness.recommendations:
                all_recs.extend(json.loads(readiness.recommendations))
            if readiness.ai_suggestions:
                all_recs.extend(json.loads(readiness.ai_suggestions))
            if all_recs:
                elements.append(Paragraph("Recommendations", section_style))
                for i, rec in enumerate(all_recs[:10], 1):
                    elements.append(Paragraph(f"{i}. {rec}", styles['Normal']))
                    elements.append(Spacer(1, 4))

        doc.build(elements)
        buffer.seek(0)
        return buffer

    @staticmethod
    def _generate_executive_summary(analysis, gap, readiness, interviews, coding_subs):
        """Generate an AI executive summary of the candidate's career readiness."""
        api_key = os.getenv("OPENAI_API_KEY")

        profile = {
            "resume_match": analysis.resume_match_score if analysis else None,
            "ats_score": analysis.ats_score if analysis else None,
            "skill_gap_match": gap.match_percentage if gap else None,
            "overall_readiness": readiness.overall_score if readiness else None,
            "interview_count": len(interviews),
            "avg_interview_score": sum(i.score or 0 for i in interviews) / len(interviews) if interviews else 0,
            "coding_submissions": len(coding_subs),
            "coding_pass_rate": sum(1 for s in coding_subs if s.status == "Accepted") / len(coding_subs) if coding_subs else 0,
        }

        if not api_key:
            return (
                f"Candidate has a resume match score of {profile['resume_match'] or 0:.1f}% "
                f"and an ATS score of {profile['ats_score'] or 0:.1f}%. "
                f"Overall career readiness stands at {profile['overall_readiness'] or 0:.1f}%. "
                f"Completed {profile['interview_count']} interviews with an average score of {profile['avg_interview_score']:.1f}/10. "
                f"Submitted {profile['coding_submissions']} coding challenges with a {profile['coding_pass_rate']*100:.1f}% pass rate."
            )

        prompt = f"""
        Generate a concise 3-4 sentence executive summary for this candidate's career readiness profile:
        - Resume Match: {profile['resume_match'] or 0:.1f}%
        - ATS Score: {profile['ats_score'] or 0:.1f}%
        - Skill Gap Match: {profile['skill_gap_match'] or 0:.1f}%
        - Overall Career Readiness: {profile['overall_readiness'] or 0:.1f}%
        - Interviews Completed: {profile['interview_count']} (avg score: {profile['avg_interview_score']:.1f}/10)
        - Coding Submissions: {profile['coding_submissions']} ({profile['coding_pass_rate']*100:.1f}% pass rate)

        Focus on strengths, key gaps, and the most impactful next step.
        """

        try:
            response = client.chat.completions.create(
                model="gpt-3.5-turbo",
                messages=[{"role": "user", "content": prompt}],
                max_tokens=200
            )
            return response.choices[0].message.content.strip()
        except Exception:
            return (
                f"Candidate demonstrates a {profile['overall_readiness'] or 0:.1f}% overall career readiness. "
                f"Key strengths include a {profile['resume_match'] or 0:.1f}% resume match and "
                f"{profile['ats_score'] or 0:.1f}% ATS compatibility. "
                f"With {profile['interview_count']} interviews completed and {profile['coding_submissions']} coding submissions, "
                f"the candidate should focus on improving weak skill areas to maximize their career potential."
            )


def _score_status(score):
    if score >= 80:
        return "Excellent"
    elif score >= 60:
        return "Good"
    elif score >= 40:
        return "Fair"
    else:
        return "Needs Work"


def generate_recruiter_hiring_report(db: Session, recruiter_id: int) -> io.BytesIO:
    """Generate a PDF hiring summary report for a recruiter."""
    from app.models.recruiter import (
        RecruiterJobPost, Application, ApplicationHistory, Shortlist, Offer
    )
    from app.models.user import User

    jobs = db.query(RecruiterJobPost).filter(
        RecruiterJobPost.recruiter_id == recruiter_id
    ).all()
    job_ids = [j.id for j in jobs]

    applications = db.query(Application).filter(
        Application.job_post_id.in_(job_ids)
    ).all() if job_ids else []

    offers = db.query(Offer).filter(
        Offer.recruiter_id == recruiter_id
    ).all()

    buffer = io.BytesIO()
    doc = ReportDocTemplate(buffer, title="Recruiter Hiring Report", pagesize=letter,
                            topMargin=0.75*inch, bottomMargin=0.75*inch)
    styles = getSampleStyleSheet()
    elements = []

    elements.append(Paragraph("Recruiter Hiring Summary Report", styles['Title']))
    elements.append(Paragraph(
        f"Generated on {datetime.now(timezone.utc).strftime('%B %d, %Y at %H:%M UTC')}",
        styles['Normal']
    ))
    elements.append(Spacer(1, 20))

    total_apps = len(applications)
    stage_counts = {}
    for a in applications:
        stage_counts[a.status] = stage_counts.get(a.status, 0) + 1

    summary_data = [
        ["Metric", "Value"],
        ["Total Job Postings", str(len(jobs))],
        ["Open Positions", str(sum(1 for j in jobs if j.status == "open"))],
        ["Total Applications", str(total_apps)],
        ["Shortlisted", str(sum(1 for a in applications if a.status in ("selected", "offer_released", "hired")))],
        ["Rejected", str(sum(1 for a in applications if a.status == "rejected"))],
        ["Hired", str(sum(1 for a in applications if a.status == "hired"))],
        ["Offers Pending", str(sum(1 for o in offers if o.status == "pending"))],
        ["Offers Accepted", str(sum(1 for o in offers if o.status == "accepted"))],
    ]
    t = Table(summary_data, colWidths=[220, 180])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1e40af')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('INNERGRID', (0, 0), (-1, -1), 0.25, colors.HexColor('#d1d5db')),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#9ca3af')),
        ('PADDING', (0, 0), (-1, -1), 8),
        ('ALIGN', (1, 0), (1, -1), 'CENTER'),
    ]))
    elements.append(Paragraph("Overview", styles['Heading2']))
    elements.append(t)
    elements.append(Spacer(1, 20))

    if stage_counts:
        elements.append(Paragraph("Pipeline Breakdown", styles['Heading2']))
        for stage, count in sorted(stage_counts.items(), key=lambda x: -x[1]):
            pct = (count / total_apps * 100) if total_apps else 0
            elements.append(Paragraph(
                f"<b>{stage.replace('_', ' ').title()}:</b> {count} ({pct:.1f}%)",
                styles['Normal']
            ))
        elements.append(Spacer(1, 20))

    if jobs:
        elements.append(Paragraph("Job Postings", styles['Heading2']))
        job_data = [["Title", "Status", "Applications", "Created"]]
        for j in jobs:
            app_count = sum(1 for a in applications if a.job_post_id == j.id)
            job_data.append([
                (j.title or "Untitled")[:40],
                j.status.title(),
                str(app_count),
                j.created_at.strftime('%Y-%m-%d') if j.created_at else "N/A",
            ])
        jt = Table(job_data, colWidths=[180, 80, 90, 100])
        jt.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1e40af')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('INNERGRID', (0, 0), (-1, -1), 0.25, colors.HexColor('#d1d5db')),
            ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#9ca3af')),
            ('PADDING', (0, 0), (-1, -1), 6),
            ('FONTSIZE', (0, 0), (-1, -1), 8),
        ]))
        elements.append(jt)
        elements.append(Spacer(1, 20))

    doc.build(elements)
    buffer.seek(0)
    return buffer
